### ISSUE TITLE
Gearset future / code contributions

### ISSUE THREAD

**Issue by PumpkinPaul** [juancampa/Gearset#3]
@juancampa Hi Juan, just want to get a feel for how you'd like to manage the changes to Gearset going forward. I'm wary of overloading you with extra work here :-)

Do you want me to create Pull Requests for any changes I make? Can I merge them myself? Or do you still want to have final say on any modifications to the toolkit?

Some things I noticed...
SolidBoxDrawer renders with a noise texture - I didn't like how this looked when drawing some charts / graphs so I've temporarily added a new copy of the class and called it "TempBoxDrawer" that renders without binding a texture. I also had to add a BIG buffer to it as I ran out of boxes - might look at a resizing / flushing option here

Lots of garbage generated - I'm not sure it's even a problem though as you'll only be running Gearset in a PROFILE / DEBUG configuration and never in RELEASE. It just made my MemoryProfiler go crazy and I still have nightmares about the XBOX360 Garbage Collector :-)

I LOVE the toolkit - it's brill - you've done a great job here - the only problem is it's stopping my working on game code as I keep thinking about new features to add.

FYI - I'm currently finalizing a gear to measure code times for performance tuning, "Profiler" - it gives you nice real time graphs of timing data for last n frames and some summary / average metrics. There's some on screen overlay 'plots' and a WPF window [ never used WPF before :-) ]

**Comment by juancampa** [comment]
Good question, I've been away from this code for some time so I need to catch up. This weekend I will be working on that. The PR model is probably the best approach as we can have an extra pair of eyes reviewing the code. I also plan to PR any work I do too.

In the case of SolidBoxDrawer we might be able to find a solution that is general enough.

In terms of GC, I don't think we should worry too much about it. There are ways to reduce the garbage generated (weak references) but if you want a memory profile you should probably disable Gearset completely.

Thanks for the feedback and for putting in the spark that actually made me turn it into an open source project which hopefully we can grow overtime.

I'd love to see/use that performance profiler. It's actually a highly requested feature.
