### ISSUE TITLE
Proposal: Profiler Gear

### ISSUE THREAD

**Issue by PumpkinPaul** [juancampa/Gearset#5]
# Overview

A new Gear for displaying real time performance metrics.

![Image of Profiler](http://www.pumpkin-games.net/images/temp_junk/ProfilerGear_1.png)
# Components

**TimerRuler** - Displays timing information for a single frame - each 'level' of category is drawn as a horizontal bar - length of the bar is the number of milliseconds an item of code takes to run.

**PerformanceGraph** - Displays timing information for the last N frames - each frame is drawn as a single bar in the chart and the timings for each of the methods are stacked vertically, indicating the total time taken for each frame for the profiled code.

**Profile Window** - Allows configuration of the Profiler gear. Displays summary information for the profiled methods.
# Usage

Call **StartFrame** at the beginning of the **Update** method to indicate a new frame has started. Wrap code to profile in **BeginMark / EndMark** calls supplying:
- **Level:** An identifier indicating the 'nesting' of the profiled code.
- **Description:** A description of the code being profiled. e.g. "Draw Particles"
- **Color:** The colour of the bar
### Example

Profile the total time taken by the Update and Draw methods. We also have two subroutines for drawing sprites and particles that we would like to profile too.

``` C#
        protected override void Update(GameTime gameTime)
        {
            GS.StartFrame();
            GS.BeginMark("Update", Color.Blue);
            //Code to udate the game
            GS.EndMark("Update");
        }

        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);

            //Begin profiling the Draw method (Level is implicitly 0)
            GS.BeginMark("Draw", Color.Red);

            //Apply nesting by specifying the Level - here it is 1
            GS.BeginMark(1, "Draw Sprites", Color.Green);
            //Draw Sprites
            GS.EndMark(1, "Draw Sprites");

            GS.BeginMark(1, "Draw Particles", Color.Yellow);
            //Draw Particles
            GS.EndMark(1, "Draw Particles");

            base.Draw(gameTime);

            GS.EndMark("Draw");
        }
```
# Source Code

The code can be found in my fork under the Profiler branch
https://github.com/PumpkinPaul/Gearset/tree/Profiler.

**Comment by juancampa** [comment]
This is great. 

Since nesting is already implied (i.e. by calling `BeginMark` twice before calling `EndMark`) I wonder if it makes sense to remove the explicit level parameter.

**Comment by PumpkinPaul** [comment]
Hmmm, I'd still have to handle recursive functions somehow as we wouldn't want to just simply increase the level each time a BeginMark was called. Maybe a dictionary of names to levels then? Something like...

``` c#
int _currentLevel = -1;
Dictionary<string, int> _nameMap = new Dictionary<string, int>();
public void BeginMark(name, color)
{
    //Look up the name in map or create a new level if this is a new name
    int level;
    if (_nameMap.ContainsKey(name)) {
        level = _nameMap[name];
    } else {
        _currentLevel++;
       level = _currentLevel;
      _nameMap[name] = level;
    }

    //...rest of code
}

public void EndMark(name)
{
    int level;
    if (_nameMap.ContainsKey(name)) {
        level = nameMap[name];
        nameMap.Remove(name);
        _currentLevel--;
    } else {
        //End called before Begin throw!
    }

    //...rest of code
}
```

**Comment by PumpkinPaul** [comment]
I've updated the branch - seems to work ok.
